- name: Install dependencies
  apt:
    name:
      - apt-transport-https # https deb repos
      - debconf # for jitsi configuration
      - debconf-utils # for jitsi configuration
    state: present
    update_cache: yes

- name: Add Jitsi Repository Signing Key
  apt_key:
    id: 66A9CD0595D6AFA247290D3BEF8B479E2DC1389C
    url: https://download.jitsi.org/jitsi-key.gpg.key
    state: present

- name: Add Jitsi Repository
  apt_repository:
    repo: deb https://download.jitsi.org stable/
    state: present

- name: Pre-configure jitsi-videobridge package
  debconf:
    name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    value: "{{ jitsi_meet_domain }}"
    vtype: string

- name: Pre-configure jitsi-meet-web-config package
  debconf:
    name: jitsi-meet-web-config
    question: jitsi-meet/cert-choice
    value: Generate a new self-signed certificate (You will later get a chance to obtain a Let's encrypt certificate)
    vtype: select

- name: Install jitsi-meet
  apt:
    name: jitsi-meet
    state: present

- name: "Configure jitsi-videobridge"
  template:
    src: sip-communicator.properties.j2
    dest: /etc/jitsi/videobridge/sip-communicator.properties
  notify: restart_jitsi